name: Docgen and go fmt

on:
  workflow_dispatch:
  push:
    branches: ['main', 'release-*']
  pull_request:

jobs:
  docgen:
    name: Verify Docgen
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.19.x'
      - run: ./scripts/verify-docs.sh
  fmt:
    name: Verify go fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.19.x'
      - run: test -z $(go fmt ./...)
